=== thriplebee/complete_xml_exercises/05. XML Definitions/XML Schema/sample.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="songs">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="song" maxOccurs="unbounded" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name">
                                <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="xs:string">
                                        <xs:attribute name="lang" type="xs:string" use="required"/>
                                      </xs:extension>
                                  </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="artist" type="xs:string"/>
                            <xs:element name="year" type="xs:int"/>
                            <xs:element name="length">
                              <xs:simpleType>
                                <xs:restriction base="xs:float">
                                  <xs:minInclusive value="1.0"/>
                                  <xs:maxInclusive value="10.0"/>
                                </xs:restriction>
                              </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="age" type="xs:int" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== thriplebee/complete_xml_exercises/05. XML Definitions/XML Schema/sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<songs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="sample.xsd">
    <song age="13">
        <name lang="en">Earth Song</name>
        <artist>Michael Jackson</artist>
        <year>1999</year>
        <length>3.5</length>
    </song>
    <song age="15">
        <name lang="en">Get Up Stand Up</name>
        <artist>Bob Marley</artist>
        <year>1990</year>
        <length>3.2</length>
    </song>
    <song age="14">
        <name lang="en">Shape Of You</name>
        <artist>Ed Sheeran</artist>
        <year>2018</year>
        <length>4.0</length>
    </song>
</songs>
